// Generated by scripts/countries/update-country-data.ts on 2026-10-09. Do not edit by hand.
// Postcodes that cross a state border, and those of the external territories, from the ABS's Postal Areas.
// Source: Australian Bureau of Statistics, Australian Statistical Geography Standard (ASGS) Edition 3, July 2021 - June 2026, Postal Areas allocation file POA_2021_AUST.xlsx (CC BY 4.0)

import type { AustralianStateCode } from "../../types/australia";

/**
 * The postcodes whose area lies in more than one state or territory, each with the states it lies in, the one with
 * most of it first. Read from the Australian Bureau of Statistics' Postal Areas (ASGS Edition 3, CC BY 4.0), which
 * approximate Australia Post's postcodes by mesh blocks, so a state with a sliver of a postcode's area is listed
 * too. An address naming any of these states passes the postcode check.
 *
 * @example
 * ```ts
 * AU_CROSS_BORDER_POSTCODES["2620"]
 * // → ["NSW","ACT"]
 * ```
 */
const AU_CROSS_BORDER_POSTCODES: Readonly<Record<string, readonly AustralianStateCode[]>> = {
  "2406": [
    "NSW",
    "QLD"
  ],
  "2611": [
    "ACT",
    "NSW"
  ],
  "2618": [
    "ACT",
    "NSW"
  ],
  "2620": [
    "NSW",
    "ACT"
  ],
  "3644": [
    "VIC",
    "NSW"
  ],
  "3691": [
    "VIC",
    "NSW"
  ],
  "3707": [
    "VIC",
    "NSW"
  ],
  "4375": [
    "QLD",
    "NSW"
  ],
  "4377": [
    "QLD",
    "NSW"
  ],
  "4380": [
    "QLD",
    "NSW"
  ],
  "4383": [
    "QLD",
    "NSW"
  ],
  "4385": [
    "QLD",
    "NSW"
  ],
  "4825": [
    "QLD",
    "NT"
  ],
  "0872": [
    "NT",
    "SA",
    "WA"
  ]
};

/**
 * The postcodes the Australian Bureau of Statistics places, wholly or partly, in the Other Territories: Jervis
 * Bay, Norfolk Island, Christmas Island and the Cocos (Keeling) Islands. Which state's code Australia Post writes
 * beside each is not in the open data, so the validator does not judge the state given with one.
 *
 * @example
 * ```ts
 * AU_EXTERNAL_TERRITORY_POSTCODES
 * // → ["2540","2899","6798","6799"]
 * ```
 */
const AU_EXTERNAL_TERRITORY_POSTCODES: readonly string[] = ["2540","2899","6798","6799"];

export { AU_CROSS_BORDER_POSTCODES, AU_EXTERNAL_TERRITORY_POSTCODES };
