// Generated by scripts/countries/update-country-data.ts on 2026-10-09. Do not edit by hand.
// The eight states and territories, by the code Australia Post writes.
// Source: kuni 1.1.0 (MIT), https://www.npmjs.com/package/@johnmorrisdotca/kuni, from Unicode CLDR and Wikidata

import type { AustralianState } from "../../types/australia";

/**
 * The six states and two territories of Australia, in order of their codes, each with Australia Post's code, the
 * ISO 3166-2 code and its name in English and in Japanese. Copied from kuni when the tables are made.
 *
 * @example
 * ```ts
 * AU_STATES.map((state) => state.code)
 * // → ["ACT","NSW","NT","QLD","SA","TAS","VIC","WA"]
 * ```
 */
const AU_STATES: readonly AustralianState[] = [
  {
    "code": "ACT",
    "iso": "AU-ACT",
    "name": "Australian Capital Territory",
    "nameJa": "オーストラリア首都特別地域",
    "kind": "territory"
  },
  {
    "code": "NSW",
    "iso": "AU-NSW",
    "name": "New South Wales",
    "nameJa": "ニューサウスウェールズ州",
    "kind": "state"
  },
  {
    "code": "NT",
    "iso": "AU-NT",
    "name": "Northern Territory",
    "nameJa": "ノーザンテリトリー",
    "kind": "territory"
  },
  {
    "code": "QLD",
    "iso": "AU-QLD",
    "name": "Queensland",
    "nameJa": "クイーンズランド州",
    "kind": "state"
  },
  {
    "code": "SA",
    "iso": "AU-SA",
    "name": "South Australia",
    "nameJa": "南オーストラリア州",
    "kind": "state"
  },
  {
    "code": "TAS",
    "iso": "AU-TAS",
    "name": "Tasmania",
    "nameJa": "タスマニア州",
    "kind": "state"
  },
  {
    "code": "VIC",
    "iso": "AU-VIC",
    "name": "Victoria",
    "nameJa": "ビクトリア州",
    "kind": "state"
  },
  {
    "code": "WA",
    "iso": "AU-WA",
    "name": "Western Australia",
    "nameJa": "西オーストラリア州",
    "kind": "state"
  }
];

export { AU_STATES };
