// The words of an Australian address, from AS4590 (Interchange of client information) as Australia Post's Address
// Presentation Standard uses it: street types, street suffixes, unit and level types, and postal delivery types. Each
// is written here as the code AS4590 gives it, in proper case, with the words and abbreviations people type for it.

/**
 * Australia's street types: each AS4590 abbreviation, in proper case as the parser reports it, with the word it
 * stands for. The parser also reads the word itself, and a few spellings people use (`Boulevarde`, `Crs`, `Tce`).
 *
 * @example
 * ```ts
 * AU_STREET_TYPES.Pde
 * // → "Parade"
 * ```
 */
const AU_STREET_TYPES: Readonly<Record<string, string>> = {
  Accs: "Access",
  Ally: "Alley",
  Alwy: "Alleyway",
  Ambl: "Amble",
  Ancg: "Anchorage",
  App: "Approach",
  Arc: "Arcade",
  Art: "Artery",
  Ave: "Avenue",
  Basn: "Basin",
  Bch: "Beach",
  Bdge: "Bridge",
  Bdwy: "Broadway",
  Bend: "Bend",
  Blk: "Block",
  Bowl: "Bowl",
  Brae: "Brae",
  Brce: "Brace",
  Brk: "Break",
  Brow: "Brow",
  Bvd: "Boulevard",
  Bypa: "Bypass",
  Bywy: "Byway",
  Caus: "Causeway",
  Cct: "Circuit",
  Cds: "Cul-de-sac",
  Ch: "Chase",
  Cir: "Circle",
  Cl: "Close",
  Clde: "Colonnade",
  Clt: "Circlet",
  Cmmn: "Common",
  Cnr: "Corner",
  Cnwy: "Centreway",
  Con: "Concourse",
  Cove: "Cove",
  Cowy: "Crossway",
  Cps: "Copse",
  Crcs: "Circus",
  Crd: "Crossroad",
  Cres: "Crescent",
  Crse: "Course",
  Crsg: "Crossing",
  Crss: "Cross",
  Crst: "Crest",
  Cso: "Corso",
  Ct: "Court",
  Ctr: "Centre",
  Cttg: "Cutting",
  Ctyd: "Courtyard",
  Cuwy: "Cruiseway",
  Dale: "Dale",
  Dell: "Dell",
  Devn: "Deviation",
  Dip: "Dip",
  Dr: "Drive",
  Drwy: "Driveway",
  Dstr: "Distributor",
  Edge: "Edge",
  Elb: "Elbow",
  End: "End",
  Ent: "Entrance",
  Esp: "Esplanade",
  Est: "Estate",
  Exp: "Expressway",
  Extn: "Extension",
  Fawy: "Fairway",
  Fitr: "Firetrail",
  Flat: "Flat",
  Folw: "Follow",
  Form: "Formation",
  Frnt: "Front",
  Frtg: "Frontage",
  Fshr: "Foreshore",
  Ftrk: "Fire Track",
  Ftwy: "Footway",
  Fwy: "Freeway",
  Gap: "Gap",
  Gdn: "Garden",
  Gdns: "Gardens",
  Gld: "Glade",
  Glen: "Glen",
  Gly: "Gully",
  Gr: "Grove",
  Gra: "Grange",
  Grn: "Green",
  Grnd: "Ground",
  Gte: "Gate",
  Gtes: "Gates",
  Gtwy: "Gateway",
  Heth: "Heath",
  Hill: "Hill",
  Hrd: "Highroad",
  Hts: "Heights",
  Hub: "Hub",
  Hwy: "Highway",
  Intg: "Interchange",
  Intn: "Intersection",
  Isld: "Island",
  Jnc: "Junction",
  Key: "Key",
  Lane: "Lane",
  Ldg: "Landing",
  Lees: "Lees",
  Line: "Line",
  Link: "Link",
  Lkt: "Lookout",
  Lnwy: "Laneway",
  Loop: "Loop",
  Lt: "Little",
  Lwr: "Lower",
  Mall: "Mall",
  Mew: "Mew",
  Mews: "Mews",
  Mndr: "Meander",
  Mt: "Mount",
  Mwy: "Motorway",
  Nook: "Nook",
  Otlk: "Outlook",
  Park: "Park",
  Part: "Part",
  Pass: "Pass",
  Path: "Path",
  Pde: "Parade",
  Phwy: "Pathway",
  Piaz: "Piazza",
  Pkld: "Parklands",
  Pkt: "Pocket",
  Pkwy: "Parkway",
  Pl: "Place",
  Plat: "Plateau",
  Plza: "Plaza",
  Pnt: "Point",
  Port: "Port",
  Prom: "Promenade",
  Prst: "Pursuit",
  Psge: "Passage",
  Qdgl: "Quadrangle",
  Qdrt: "Quadrant",
  Quad: "Quad",
  Qy: "Quay",
  Qys: "Quays",
  Ramp: "Ramp",
  Rch: "Reach",
  Rd: "Road",
  Rdge: "Ridge",
  Rds: "Roads",
  Rdsd: "Roadside",
  Rdwy: "Roadway",
  Res: "Reserve",
  Rest: "Rest",
  Rgwy: "Ridgeway",
  Ride: "Ride",
  Ring: "Ring",
  Rise: "Rise",
  Rmbl: "Ramble",
  Rnd: "Round",
  Rnde: "Ronde",
  Rnge: "Range",
  Row: "Row",
  Rowy: "Right of Way",
  Rsbl: "Rosebowl",
  Rte: "Route",
  Rtt: "Retreat",
  Rty: "Rotary",
  Rue: "Rue",
  Run: "Run",
  Rvr: "River",
  Rvra: "Riviera",
  Rvwy: "Riverway",
  Sbwy: "Subway",
  Sdng: "Siding",
  Shwy: "State Highway",
  Slpe: "Slope",
  Snd: "Sound",
  Spur: "Spur",
  Sq: "Square",
  St: "Street",
  Stps: "Steps",
  Stra: "Strand",
  Strp: "Strip",
  Strs: "Stairs",
  Swy: "Service Way",
  Tarn: "Tarn",
  Tce: "Terrace",
  Thor: "Thoroughfare",
  Tkwy: "Trunkway",
  Tlwy: "Tollway",
  Top: "Top",
  Tor: "Tor",
  Tri: "Triangle",
  Trk: "Track",
  Trl: "Trail",
  Trlr: "Trailer",
  Turn: "Turn",
  Twrs: "Towers",
  Upas: "Underpass",
  Upr: "Upper",
  Vale: "Vale",
  Vdct: "Viaduct",
  View: "View",
  Vll: "Villa",
  Vlls: "Villas",
  Vsta: "Vista",
  Wade: "Wade",
  Walk: "Walk",
  Way: "Way",
  Whrf: "Wharf",
  Wkwy: "Walkway",
  Wood: "Wood",
  Wtrs: "Waters",
  Wynd: "Wynd",
  Yard: "Yard",
};

// Other spellings of a street type people write, to its AS4590 abbreviation.
const AU_STREET_TYPE_VARIANTS: Readonly<Record<string, string>> = {
  AV: "Ave",
  BLVD: "Bvd",
  BOULEVARDE: "Bvd",
  BVDE: "Bvd",
  CIRC: "Cct",
  CR: "Cres",
  CRS: "Cres",
  CRESC: "Cres",
  DRV: "Dr",
  GV: "Gr",
  GVE: "Gr",
  HWAY: "Hwy",
  LN: "Lane",
  PDE: "Pde",
  PK: "Park",
  PWY: "Pkwy",
  STR: "St",
  TCE: "Tce",
  TERR: "Tce",
};

// The street suffixes of AS4590: a direction or a qualifier written after the street type.
const AU_STREET_SUFFIXES: Readonly<Record<string, string>> = {
  CENTRAL: "CN",
  CN: "CN",
  E: "E",
  EAST: "E",
  EX: "EX",
  EXTENSION: "EX",
  LOWER: "LR",
  LR: "LR",
  N: "N",
  NE: "NE",
  NORTH: "N",
  "NORTH EAST": "NE",
  "NORTH WEST": "NW",
  NORTHEAST: "NE",
  NORTHWEST: "NW",
  NW: "NW",
  S: "S",
  SE: "SE",
  SOUTH: "S",
  "SOUTH EAST": "SE",
  "SOUTH WEST": "SW",
  SOUTHEAST: "SE",
  SOUTHWEST: "SW",
  SW: "SW",
  UP: "UP",
  UPPER: "UP",
  W: "W",
  WEST: "W",
};

// AS4590's flat and unit types, by the word the parser reports, with the codes and spellings it reads for each.
const AU_UNIT_TYPES: Readonly<Record<string, readonly string[]>> = {
  Apartment: ["APT", "APARTMENT"],
  Cottage: ["CTGE", "COTTAGE"],
  Duplex: ["DUP", "DUPLEX"],
  Factory: ["FY", "FACTORY"],
  Flat: ["F", "FLAT"],
  House: ["HSE"],
  Kiosk: ["KSK", "KIOSK"],
  Maisonette: ["MSNT", "MAISONETTE"],
  "Marine Berth": ["MB", "MARINE BERTH"],
  Office: ["OFF", "OFFICE"],
  Penthouse: ["PTHS", "PENTHOUSE"],
  Room: ["RM", "ROOM"],
  Shed: ["SHED"],
  Shop: ["SHOP"],
  Site: ["SITE"],
  Stall: ["SL", "STALL"],
  Studio: ["STU", "STUDIO"],
  Suite: ["SE", "STE", "SUITE"],
  Townhouse: ["TNHS", "TOWNHOUSE"],
  Unit: ["U", "UNIT"],
  Villa: ["VLLA", "VILLA"],
  Ward: ["WARD"],
  Warehouse: ["WE", "WAREHOUSE"],
};

// AS4590's floor and level types, by the words the parser reports, with what it reads for each. A one-letter code
// (B, G, L, M) is read only before a number.
const AU_LEVEL_TYPES: Readonly<Record<string, readonly string[]>> = {
  Basement: ["B", "BASEMENT"],
  Floor: ["FL", "FLR", "FLOOR"],
  "Ground Floor": ["G", "GROUND FLOOR", "GROUND"],
  Level: ["L", "LVL", "LEV", "LEVEL"],
  "Lower Ground Floor": ["LG", "LOWER GROUND FLOOR", "LOWER GROUND"],
  Mezzanine: ["M", "MEZZ", "MEZZANINE"],
  "Upper Ground Floor": ["UG", "UPPER GROUND FLOOR", "UPPER GROUND"],
};

// AS4590's postal delivery types, by the form the parser reports (Australia Post's, as written on an envelope), with
// the spellings it reads for each.
const AU_POSTAL_DELIVERY_TYPES: Readonly<Record<string, readonly string[]>> = {
  "Care PO": ["CARE PO", "CARE OF POST OFFICE", "C/- POST OFFICE", "C/O POST OFFICE", "C/- PO", "C/O PO"],
  CMA: ["CMA", "COMMUNITY MAIL AGENT"],
  CMB: ["CMB", "COMMUNITY MAIL BAG"],
  CPA: ["CPA", "COMMUNITY POSTAL AGENT"],
  "GPO Box": ["GPO BOX", "G P O BOX", "G.P.O. BOX", "GENERAL POST OFFICE BOX"],
  "Locked Bag": ["LOCKED BAG", "LOCKED MAIL BAG", "LMB"],
  MS: ["MS", "MAIL SERVICE"],
  "PO Box": ["PO BOX", "P O BOX", "P.O. BOX", "POST OFFICE BOX", "POBOX", "BOX"],
  "Private Bag": ["PRIVATE BAG", "PRIVATE MAIL BAG", "PMB"],
  RMB: ["RMB", "ROADSIDE MAIL BOX", "ROADSIDE MAIL BAG"],
  RMS: ["RMS", "ROADSIDE MAIL SERVICE"],
  RSD: ["RSD", "ROADSIDE DELIVERY"],
};

export {
  AU_LEVEL_TYPES,
  AU_POSTAL_DELIVERY_TYPES,
  AU_STREET_SUFFIXES,
  AU_STREET_TYPES,
  AU_STREET_TYPE_VARIANTS,
  AU_UNIT_TYPES,
};
