// Generated by scripts/countries/update-country-data.ts on 2026-10-10. Do not edit by hand.
// The sixteen Länder of Germany.
// Source: kuni 1.1.0 (MIT), https://www.npmjs.com/package/@johnmorrisdotca/kuni, from Unicode CLDR and Wikidata

import type { GermanState } from "../../types/germany";

/**
 * The sixteen Länder of Germany, in order of their codes, each with its ISO 3166-2 code and its name in English
 * and in Japanese. Copied from kuni when the tables are made.
 *
 * @example
 * ```ts
 * DE_STATES.map((state) => state.code)
 * // → ["BB","BE","BW","BY","HB","HE","HH","MV","NI","NW","RP","SH","SL","SN","ST","TH"]
 * ```
 */
const DE_STATES: readonly GermanState[] = [
  {
    "code": "BB",
    "iso": "DE-BB",
    "name": "Brandenburg",
    "nameJa": "ブランデンブルク州"
  },
  {
    "code": "BE",
    "iso": "DE-BE",
    "name": "Berlin",
    "nameJa": "ベルリン"
  },
  {
    "code": "BW",
    "iso": "DE-BW",
    "name": "Baden-Württemberg",
    "nameJa": "バーデン＝ヴュルテンベルク州"
  },
  {
    "code": "BY",
    "iso": "DE-BY",
    "name": "Bavaria",
    "nameJa": "バイエルン自由州"
  },
  {
    "code": "HB",
    "iso": "DE-HB",
    "name": "Bremen",
    "nameJa": "ブレーメン州"
  },
  {
    "code": "HE",
    "iso": "DE-HE",
    "name": "Hesse",
    "nameJa": "ヘッセン州"
  },
  {
    "code": "HH",
    "iso": "DE-HH",
    "name": "Hamburg",
    "nameJa": "ハンブルク"
  },
  {
    "code": "MV",
    "iso": "DE-MV",
    "name": "Mecklenburg-Vorpommern",
    "nameJa": "メクレンブルク＝フォアポンメルン州"
  },
  {
    "code": "NI",
    "iso": "DE-NI",
    "name": "Lower Saxony",
    "nameJa": "ニーダーザクセン州"
  },
  {
    "code": "NW",
    "iso": "DE-NW",
    "name": "North Rhine-Westphalia",
    "nameJa": "ノルトライン＝ヴェストファーレン州"
  },
  {
    "code": "RP",
    "iso": "DE-RP",
    "name": "Rhineland-Palatinate",
    "nameJa": "ラインラント＝プファルツ州"
  },
  {
    "code": "SH",
    "iso": "DE-SH",
    "name": "Schleswig-Holstein",
    "nameJa": "シュレースヴィヒ＝ホルシュタイン州"
  },
  {
    "code": "SL",
    "iso": "DE-SL",
    "name": "Saarland",
    "nameJa": "ザールラント州"
  },
  {
    "code": "SN",
    "iso": "DE-SN",
    "name": "Saxony",
    "nameJa": "ザクセン州"
  },
  {
    "code": "ST",
    "iso": "DE-ST",
    "name": "Saxony-Anhalt",
    "nameJa": "ザクセン＝アンハルト州"
  },
  {
    "code": "TH",
    "iso": "DE-TH",
    "name": "Thuringia",
    "nameJa": "テューリンゲン州"
  }
];

export { DE_STATES };
