// Generated by scripts/jp/update-jp-data.ts on 2026-10-09. Do not edit by hand.
// The 47 prefectures, in JIS X 0401 order.
// Source: Geolonia 住所データ (MIT), https://github.com/geolonia/japanese-addresses

import type { JapanesePrefecture } from "../../types/japan";

/**
 * The 47 prefectures in JIS X 0401 order, each with its code, official name, katakana reading and romaji.
 * Generated from Geolonia 住所データ (MIT).
 *
 * @example
 * ```ts
 * JP_PREFECTURES.length
 * // → 47
 * ```
 */
const JP_PREFECTURES: readonly JapanesePrefecture[] = [
  {
    "code": "01",
    "name": "北海道",
    "kana": "ホッカイドウ",
    "romaji": "Hokkaido"
  },
  {
    "code": "02",
    "name": "青森県",
    "kana": "アオモリケン",
    "romaji": "Aomori-ken"
  },
  {
    "code": "03",
    "name": "岩手県",
    "kana": "イワテケン",
    "romaji": "Iwate-ken"
  },
  {
    "code": "04",
    "name": "宮城県",
    "kana": "ミヤギケン",
    "romaji": "Miyagi-ken"
  },
  {
    "code": "05",
    "name": "秋田県",
    "kana": "アキタケン",
    "romaji": "Akita-ken"
  },
  {
    "code": "06",
    "name": "山形県",
    "kana": "ヤマガタケン",
    "romaji": "Yamagata-ken"
  },
  {
    "code": "07",
    "name": "福島県",
    "kana": "フクシマケン",
    "romaji": "Fukushima-ken"
  },
  {
    "code": "08",
    "name": "茨城県",
    "kana": "イバラキケン",
    "romaji": "Ibaraki-ken"
  },
  {
    "code": "09",
    "name": "栃木県",
    "kana": "トチギケン",
    "romaji": "Tochigi-ken"
  },
  {
    "code": "10",
    "name": "群馬県",
    "kana": "グンマケン",
    "romaji": "Gumma-ken"
  },
  {
    "code": "11",
    "name": "埼玉県",
    "kana": "サイタマケン",
    "romaji": "Saitama-ken"
  },
  {
    "code": "12",
    "name": "千葉県",
    "kana": "チバケン",
    "romaji": "Chiba-ken"
  },
  {
    "code": "13",
    "name": "東京都",
    "kana": "トウキョウト",
    "romaji": "Tokyo-to"
  },
  {
    "code": "14",
    "name": "神奈川県",
    "kana": "カナガワケン",
    "romaji": "Kanagawa-ken"
  },
  {
    "code": "15",
    "name": "新潟県",
    "kana": "ニイガタケン",
    "romaji": "Niigata-ken"
  },
  {
    "code": "16",
    "name": "富山県",
    "kana": "トヤマケン",
    "romaji": "Toyama-ken"
  },
  {
    "code": "17",
    "name": "石川県",
    "kana": "イシカワケン",
    "romaji": "Ishikawa-ken"
  },
  {
    "code": "18",
    "name": "福井県",
    "kana": "フクイケン",
    "romaji": "Fukui-ken"
  },
  {
    "code": "19",
    "name": "山梨県",
    "kana": "ヤマナシケン",
    "romaji": "Yamanashi-ken"
  },
  {
    "code": "20",
    "name": "長野県",
    "kana": "ナガノケン",
    "romaji": "Nagano-ken"
  },
  {
    "code": "21",
    "name": "岐阜県",
    "kana": "ギフケン",
    "romaji": "Gifu-ken"
  },
  {
    "code": "22",
    "name": "静岡県",
    "kana": "シズオカケン",
    "romaji": "Shizuoka-ken"
  },
  {
    "code": "23",
    "name": "愛知県",
    "kana": "アイチケン",
    "romaji": "Aichi-ken"
  },
  {
    "code": "24",
    "name": "三重県",
    "kana": "ミエケン",
    "romaji": "Mie-ken"
  },
  {
    "code": "25",
    "name": "滋賀県",
    "kana": "シガケン",
    "romaji": "Shiga-ken"
  },
  {
    "code": "26",
    "name": "京都府",
    "kana": "キョウトフ",
    "romaji": "Kyoto-fu"
  },
  {
    "code": "27",
    "name": "大阪府",
    "kana": "オオサカフ",
    "romaji": "Osaka-fu"
  },
  {
    "code": "28",
    "name": "兵庫県",
    "kana": "ヒョウゴケン",
    "romaji": "Hyogo-ken"
  },
  {
    "code": "29",
    "name": "奈良県",
    "kana": "ナラケン",
    "romaji": "Nara-ken"
  },
  {
    "code": "30",
    "name": "和歌山県",
    "kana": "ワカヤマケン",
    "romaji": "Wakayama-ken"
  },
  {
    "code": "31",
    "name": "鳥取県",
    "kana": "トットリケン",
    "romaji": "Tottori-ken"
  },
  {
    "code": "32",
    "name": "島根県",
    "kana": "シマネケン",
    "romaji": "Shimane-ken"
  },
  {
    "code": "33",
    "name": "岡山県",
    "kana": "オカヤマケン",
    "romaji": "Okayama-ken"
  },
  {
    "code": "34",
    "name": "広島県",
    "kana": "ヒロシマケン",
    "romaji": "Hiroshima-ken"
  },
  {
    "code": "35",
    "name": "山口県",
    "kana": "ヤマグチケン",
    "romaji": "Yamaguchi-ken"
  },
  {
    "code": "36",
    "name": "徳島県",
    "kana": "トクシマケン",
    "romaji": "Tokushima-ken"
  },
  {
    "code": "37",
    "name": "香川県",
    "kana": "カガワケン",
    "romaji": "Kagawa-ken"
  },
  {
    "code": "38",
    "name": "愛媛県",
    "kana": "エヒメケン",
    "romaji": "Ehime-ken"
  },
  {
    "code": "39",
    "name": "高知県",
    "kana": "コウチケン",
    "romaji": "Kochi-ken"
  },
  {
    "code": "40",
    "name": "福岡県",
    "kana": "フクオカケン",
    "romaji": "Fukuoka-ken"
  },
  {
    "code": "41",
    "name": "佐賀県",
    "kana": "サガケン",
    "romaji": "Saga-ken"
  },
  {
    "code": "42",
    "name": "長崎県",
    "kana": "ナガサキケン",
    "romaji": "Nagasaki-ken"
  },
  {
    "code": "43",
    "name": "熊本県",
    "kana": "クマモトケン",
    "romaji": "Kumamoto-ken"
  },
  {
    "code": "44",
    "name": "大分県",
    "kana": "オオイタケン",
    "romaji": "Oita-ken"
  },
  {
    "code": "45",
    "name": "宮崎県",
    "kana": "ミヤザキケン",
    "romaji": "Miyazaki-ken"
  },
  {
    "code": "46",
    "name": "鹿児島県",
    "kana": "カゴシマケン",
    "romaji": "Kagoshima-ken"
  },
  {
    "code": "47",
    "name": "沖縄県",
    "kana": "オキナワケン",
    "romaji": "Okinawa-ken"
  }
];

export { JP_PREFECTURES };
