// Generated by scripts/countries/update-country-data.ts on 2026-10-09. Do not edit by hand.
// The postcode districts of Great Britain and the nations they lie in, from Code-Point Open.
// Source: Ordnance Survey Code-Point Open (Open Government Licence v3.0). Contains OS data © Crown copyright and database right 2026. Contains Royal Mail data © Royal Mail copyright and database right 2026. Contains National Statistics data © Crown copyright and database right 2026.

import type { UKNationCode } from "../../types/united-kingdom";

/**
 * Every postcode district in Great Britain, by area: the numbered districts as runs, then those with a letter.
 * Read from Ordnance Survey's Code-Point Open (OGL v3; contains Royal Mail data © Royal Mail copyright and
 * database right). Northern Ireland's BT area is not in it, so its districts are not listed.
 *
 * @example
 * ```ts
 * GB_POSTCODE_DISTRICTS["EC"]
 * // → "1A,1M,1N,1P,1R,1V,1Y,2A,2M,2N,2P,2R,2V,2Y,3A,3M,3N,3P,3R,3V,4A,4M,4N,4P,4R,4V,4Y"
 * ```
 */
const GB_POSTCODE_DISTRICTS: Readonly<Record<string, string>> = {
  "AB": "10-16,21-25,30-39,41-45,51-56,99",
  "AL": "1-10",
  "B": "1-21,23-38,40,42-50,60-80,90-99",
  "BA": "1-16,20-22",
  "BB": "1-12,18",
  "BD": "1-24,97-99",
  "BH": "1-25,31",
  "BL": "0-9,11,78",
  "BN": "1-3,5-18,20-27,41-45,50-52,88,91,95,99",
  "BR": "1-8",
  "BS": "1-11,13-16,20-32,34-37,39-41,48-49,98-99",
  "CA": "1-28,95",
  "CB": "1-11,21-25",
  "CF": "3,5,10-11,14-15,23-24,30-48,61-64,71-72,81-83,91,95,99",
  "CH": "1-8,25-34,41-49,60-66,70,88,90,99",
  "CM": "0-9,11-24,77,92,98-99",
  "CO": "1-16",
  "CR": "0,2-9,90",
  "CT": "1-21,50",
  "CV": "1-13,21-23,31-37,47",
  "CW": "1-12,98",
  "DA": "1-18",
  "DD": "1-11",
  "DE": "1,3-7,11-15,21-24,45,55-56,65,72-75,99",
  "DG": "1-14,16",
  "DH": "1-9,97-99",
  "DL": "1-17,98",
  "DN": "1-12,14-22,31-41",
  "DT": "1-11",
  "DY": "1-14",
  "E": "1-18,20,22,98,1W",
  "EC": "1A,1M,1N,1P,1R,1V,1Y,2A,2M,2N,2P,2R,2V,2Y,3A,3M,3N,3P,3R,3V,4A,4M,4N,4P,4R,4V,4Y",
  "EH": "1-49,51-55,91,95,99",
  "EN": "1-11,77",
  "EX": "1-24,31-39",
  "FK": "1-21",
  "FY": "1-8",
  "G": "1-5,11-15,20-23,31-34,40-46,51-53,58,60-79,81-84,90",
  "GL": "1-20,50-56",
  "GU": "1-12,14-35,46-47,51-52",
  "HA": "0-9",
  "HD": "1-9",
  "HG": "1-5",
  "HP": "1-23,27",
  "HR": "1-9",
  "HS": "1-9",
  "HU": "1-20",
  "HX": "1-7",
  "IG": "1-11",
  "IP": "1-33,98",
  "IV": "1-28,30-32,36,40-49,51-56,63,99",
  "KA": "1-30",
  "KT": "1-24",
  "KW": "1-3,5-17",
  "KY": "1-16,99",
  "L": "1-40,67-72,74-75",
  "LA": "1-23",
  "LD": "1-8",
  "LE": "1-19,21,41,65,67,87,94-95",
  "LL": "11-49,51-78",
  "LN": "1-13",
  "LS": "1-29,78,88,98-99",
  "LU": "1-7",
  "M": "1-9,11-35,38,40-41,43-46,50,60-61,90,99",
  "ME": "1-20",
  "MK": "1-20,40-46,77",
  "ML": "1-12",
  "N": "1-22,81,1C,1P",
  "NE": "1-13,15-49,61-71,85,88,92,98-99",
  "NG": "1-25,31-34,80,90",
  "NN": "1-18,29",
  "NP": "4,7-8,10-13,15-16,18-20,22-26,44",
  "NR": "1-35,99",
  "NW": "1-11,26,1W",
  "OL": "1-16",
  "OX": "1-5,7,9-18,20,25-29,33,39,44,49",
  "PA": "1-38,41-49,60-78,80",
  "PE": "1-16,19-38",
  "PH": "1-26,30-44,49-50",
  "PL": "1-35,95",
  "PO": "1-22,24,30-41",
  "PR": "0-9,11,25-26",
  "RG": "1-2,4-10,12,14,17-31,40-42,45",
  "RH": "1-20,77",
  "RM": "1-20",
  "S": "1-14,17-18,20-21,25-26,32-33,35-36,40-45,49,60-66,70-75,80-81,94-99",
  "SA": "1-20,31-48,61-73,80,99",
  "SE": "1-28,1P",
  "SG": "1-19",
  "SK": "1-17,22-23",
  "SL": "0-9,60,95",
  "SM": "1-7",
  "SN": "1-16,25-26,38,80,99",
  "SO": "14-25,30-32,40-43,45,50-53,97",
  "SP": "1-11",
  "SR": "1-8,43",
  "SS": "0-9,11-17,22,99",
  "ST": "1-21,55",
  "SW": "2-20,95,1A,1E,1H,1P,1V,1W,1X,1Y",
  "SY": "1-25,99",
  "TA": "1-24",
  "TD": "1-15",
  "TF": "1-13",
  "TN": "1-40",
  "TQ": "1-14",
  "TR": "1-27",
  "TS": "1-29",
  "TW": "1-20,98",
  "UB": "1-11,18",
  "W": "2-14,1A,1B,1C,1D,1F,1G,1H,1J,1K,1S,1T,1U,1W",
  "WA": "1-16,55,88",
  "WC": "1A,1B,1E,1H,1N,1R,1V,1X,2A,2B,2E,2H,2N,2R",
  "WD": "3-7,17-19,23-25,99",
  "WF": "1-17,90",
  "WN": "1-8",
  "WR": "1-15,99",
  "WS": "1-15",
  "WV": "1-16,98-99",
  "YO": "1,7-8,10-19,21-26,30-32,41-43,51,60-62,90",
  "ZE": "1-3"
};

/**
 * The nation each postcode area of Great Britain delivers to, by the most of its postcodes. The districts that
 * cross a border are listed in GB_CROSS_BORDER_DISTRICTS. From Code-Point Open (OGL v3).
 *
 * @example
 * ```ts
 * GB_AREA_NATIONS["CF"]
 * // → "WLS"
 * ```
 */
const GB_AREA_NATIONS: Readonly<Record<string, UKNationCode>> = {
  "AB": "SCT",
  "AL": "ENG",
  "B": "ENG",
  "BA": "ENG",
  "BB": "ENG",
  "BD": "ENG",
  "BH": "ENG",
  "BL": "ENG",
  "BN": "ENG",
  "BR": "ENG",
  "BS": "ENG",
  "CA": "ENG",
  "CB": "ENG",
  "CF": "WLS",
  "CH": "ENG",
  "CM": "ENG",
  "CO": "ENG",
  "CR": "ENG",
  "CT": "ENG",
  "CV": "ENG",
  "CW": "ENG",
  "DA": "ENG",
  "DD": "SCT",
  "DE": "ENG",
  "DG": "SCT",
  "DH": "ENG",
  "DL": "ENG",
  "DN": "ENG",
  "DT": "ENG",
  "DY": "ENG",
  "E": "ENG",
  "EC": "ENG",
  "EH": "SCT",
  "EN": "ENG",
  "EX": "ENG",
  "FK": "SCT",
  "FY": "ENG",
  "G": "SCT",
  "GL": "ENG",
  "GU": "ENG",
  "HA": "ENG",
  "HD": "ENG",
  "HG": "ENG",
  "HP": "ENG",
  "HR": "ENG",
  "HS": "SCT",
  "HU": "ENG",
  "HX": "ENG",
  "IG": "ENG",
  "IP": "ENG",
  "IV": "SCT",
  "KA": "SCT",
  "KT": "ENG",
  "KW": "SCT",
  "KY": "SCT",
  "L": "ENG",
  "LA": "ENG",
  "LD": "WLS",
  "LE": "ENG",
  "LL": "WLS",
  "LN": "ENG",
  "LS": "ENG",
  "LU": "ENG",
  "M": "ENG",
  "ME": "ENG",
  "MK": "ENG",
  "ML": "SCT",
  "N": "ENG",
  "NE": "ENG",
  "NG": "ENG",
  "NN": "ENG",
  "NP": "WLS",
  "NR": "ENG",
  "NW": "ENG",
  "OL": "ENG",
  "OX": "ENG",
  "PA": "SCT",
  "PE": "ENG",
  "PH": "SCT",
  "PL": "ENG",
  "PO": "ENG",
  "PR": "ENG",
  "RG": "ENG",
  "RH": "ENG",
  "RM": "ENG",
  "S": "ENG",
  "SA": "WLS",
  "SE": "ENG",
  "SG": "ENG",
  "SK": "ENG",
  "SL": "ENG",
  "SM": "ENG",
  "SN": "ENG",
  "SO": "ENG",
  "SP": "ENG",
  "SR": "ENG",
  "SS": "ENG",
  "ST": "ENG",
  "SW": "ENG",
  "SY": "ENG",
  "TA": "ENG",
  "TD": "SCT",
  "TF": "ENG",
  "TN": "ENG",
  "TQ": "ENG",
  "TR": "ENG",
  "TS": "ENG",
  "TW": "ENG",
  "UB": "ENG",
  "W": "ENG",
  "WA": "ENG",
  "WC": "ENG",
  "WD": "ENG",
  "WF": "ENG",
  "WN": "ENG",
  "WR": "ENG",
  "WS": "ENG",
  "WV": "ENG",
  "YO": "ENG",
  "ZE": "SCT"
};

/**
 * The postcode districts not wholly in the nation of their area, each with the nations its postcodes lie in, the
 * one with most of them first: the districts that cross the borders of Wales and of Scotland, and those wholly
 * across one (CH5 to CH8 are in Wales, though most of the CH area is in England). From Code-Point Open (OGL v3).
 *
 * @example
 * ```ts
 * [GB_DISTRICT_NATIONS["TD15"], GB_DISTRICT_NATIONS["CH5"]]
 * // → [["ENG","SCT"],["WLS"]]
 * ```
 */
const GB_DISTRICT_NATIONS: Readonly<Record<string, readonly UKNationCode[]>> = {
  "CH1": [
    "ENG",
    "WLS"
  ],
  "CH4": [
    "ENG",
    "WLS"
  ],
  "CH5": [
    "WLS"
  ],
  "CH6": [
    "WLS"
  ],
  "CH7": [
    "WLS"
  ],
  "CH8": [
    "WLS"
  ],
  "DG16": [
    "SCT",
    "ENG"
  ],
  "GL16": [
    "ENG",
    "WLS"
  ],
  "HR3": [
    "ENG",
    "WLS"
  ],
  "HR5": [
    "ENG",
    "WLS"
  ],
  "LD7": [
    "WLS",
    "ENG"
  ],
  "LD8": [
    "WLS",
    "ENG"
  ],
  "LL14": [
    "WLS",
    "ENG"
  ],
  "NP16": [
    "WLS",
    "ENG"
  ],
  "NP25": [
    "WLS",
    "ENG"
  ],
  "NP7": [
    "WLS",
    "ENG"
  ],
  "SY10": [
    "ENG",
    "WLS"
  ],
  "SY13": [
    "ENG",
    "WLS"
  ],
  "SY14": [
    "ENG",
    "WLS"
  ],
  "SY15": [
    "WLS",
    "ENG"
  ],
  "SY16": [
    "WLS"
  ],
  "SY17": [
    "WLS"
  ],
  "SY18": [
    "WLS"
  ],
  "SY19": [
    "WLS"
  ],
  "SY20": [
    "WLS"
  ],
  "SY21": [
    "WLS",
    "ENG"
  ],
  "SY22": [
    "WLS",
    "ENG"
  ],
  "SY23": [
    "WLS"
  ],
  "SY24": [
    "WLS"
  ],
  "SY25": [
    "WLS"
  ],
  "SY5": [
    "ENG",
    "WLS"
  ],
  "SY7": [
    "ENG",
    "WLS"
  ],
  "SY9": [
    "ENG",
    "WLS"
  ],
  "TD12": [
    "SCT",
    "ENG"
  ],
  "TD15": [
    "ENG",
    "SCT"
  ],
  "TD5": [
    "SCT",
    "ENG"
  ],
  "TD9": [
    "SCT",
    "ENG"
  ]
};

export { GB_AREA_NATIONS, GB_DISTRICT_NATIONS, GB_POSTCODE_DISTRICTS };
