// Generated by scripts/countries/update-country-data.ts on 2026-10-09. Do not edit by hand.
// The four nations of the United Kingdom.
// Source: kuni 1.1.0 (MIT), https://www.npmjs.com/package/@johnmorrisdotca/kuni, from Unicode CLDR and Wikidata

import type { UKNation } from "../../types/united-kingdom";

/**
 * The four nations of the United Kingdom, in order of their codes, each with its ISO 3166-2 code and its name in
 * English and in Japanese. Copied from kuni when the tables are made.
 *
 * @example
 * ```ts
 * GB_NATIONS.map((nation) => nation.name)
 * // → ["England","Northern Ireland","Scotland","Wales"]
 * ```
 */
const GB_NATIONS: readonly UKNation[] = [
  {
    "code": "ENG",
    "iso": "GB-ENG",
    "name": "England",
    "nameJa": "イングランド"
  },
  {
    "code": "NIR",
    "iso": "GB-NIR",
    "name": "Northern Ireland",
    "nameJa": "北アイルランド"
  },
  {
    "code": "SCT",
    "iso": "GB-SCT",
    "name": "Scotland",
    "nameJa": "スコットランド"
  },
  {
    "code": "WLS",
    "iso": "GB-WLS",
    "name": "Wales",
    "nameJa": "ウェールズ"
  }
];

export { GB_NATIONS };
