// The words of an address in the United Kingdom: the thoroughfare descriptors the parser splits from a street's name,
// the abbreviations people type for them, and the counties that may be written before the postcode. Written here in
// our own words from Royal Mail's addressing guidance; Royal Mail writes descriptors in full.

/**
 * The thoroughfare descriptors the parser takes off the end of a street's name and reports, in full, as `type`
 * (`High Street` is street `High`, type `Street`), with the abbreviations it reads for each. A street ending in none
 * of them (`Kingsway`, `The Strand`) has no type.
 *
 * @example
 * ```ts
 * GB_THOROUGHFARE_DESCRIPTORS.Road
 * // → ["RD"]
 * ```
 */
const GB_THOROUGHFARE_DESCRIPTORS: Readonly<Record<string, readonly string[]>> = {
  Approach: ["APP", "APPR"],
  Avenue: ["AVE", "AV"],
  Bank: [],
  Boulevard: ["BLVD", "BVD"],
  Broadway: [],
  Brow: [],
  Bypass: [],
  Causeway: [],
  Chase: [],
  Circus: [],
  Close: ["CL"],
  Common: [],
  Copse: [],
  Corner: [],
  Cottages: ["COTTS"],
  Court: ["CT"],
  Crescent: ["CRES", "CRESC"],
  Croft: [],
  Dale: [],
  Dell: [],
  Drive: ["DR"],
  Drove: [],
  Embankment: [],
  End: [],
  Esplanade: ["ESP"],
  Fields: [],
  Fold: [],
  Gardens: ["GDNS"],
  Gate: [],
  Glade: [],
  Glen: [],
  Green: ["GN", "GRN"],
  Grove: ["GR", "GRO", "GRV"],
  Heights: ["HTS"],
  Highway: ["HWY"],
  Hill: [],
  Hollow: [],
  Lane: ["LN"],
  Link: [],
  Loke: [],
  Mall: [],
  Mead: [],
  Meadow: [],
  Meadows: [],
  Mews: [],
  Mount: ["MT"],
  Orchard: [],
  Oval: [],
  Paddock: [],
  Parade: ["PDE"],
  Park: ["PK"],
  Passage: [],
  Path: [],
  Place: ["PL"],
  Promenade: ["PROM"],
  Quay: [],
  Rise: [],
  Road: ["RD"],
  Row: [],
  Square: ["SQ"],
  Street: ["ST", "STR"],
  Terrace: ["TERR", "TCE"],
  Vale: [],
  View: [],
  Walk: ["WLK"],
  Way: ["WY"],
  Wharf: [],
  Wynd: [],
  Yard: [],
};

// Counties that may be written before the postcode: the old postal counties, England's ceremonial counties, Scotland's
// traditional counties, Wales's preserved counties and principal areas, Northern Ireland's six counties, and the
// short forms people use. Royal Mail no longer needs a county, so one is reported apart and never taken for the town.
// A county that shares its name with a post town (Durham, Antrim, Armagh, Caerphilly, Bridgend, Conwy, Londonderry) is
// listed only in its "County" form, so the town is never taken for a county.
const GB_COUNTIES: readonly string[] = [
  "Aberdeenshire",
  "Anglesey",
  "Angus",
  "Argyll",
  "Argyll and Bute",
  "Avon",
  "Ayrshire",
  "Banffshire",
  "Beds",
  "Bedfordshire",
  "Berks",
  "Berkshire",
  "Berwickshire",
  "Blaenau Gwent",
  "Bucks",
  "Buckinghamshire",
  "Caithness",
  "Cambs",
  "Cambridgeshire",
  "Carmarthenshire",
  "Ceredigion",
  "Cheshire",
  "Cheshire East",
  "Cheshire West and Chester",
  "Clackmannanshire",
  "Cleveland",
  "Clwyd",
  "Co Antrim",
  "Co Armagh",
  "Co Down",
  "Co Durham",
  "Co Fermanagh",
  "Co Londonderry",
  "Co Tyrone",
  "Cornwall",
  "County Antrim",
  "County Armagh",
  "County Down",
  "County Durham",
  "County Fermanagh",
  "County Londonderry",
  "County Tyrone",
  "Cumbria",
  "Denbighshire",
  "Derbyshire",
  "Devon",
  "Dorset",
  "Dumfries and Galloway",
  "Dumfriesshire",
  "Dunbartonshire",
  "Dyfed",
  "E Sussex",
  "East Lothian",
  "East Riding of Yorkshire",
  "East Sussex",
  "East Yorkshire",
  "Essex",
  "Fife",
  "Flintshire",
  "Glamorgan",
  "Glos",
  "Gloucestershire",
  "Greater London",
  "Greater Manchester",
  "Gwent",
  "Gwynedd",
  "Hants",
  "Hampshire",
  "Herefordshire",
  "Herts",
  "Hertfordshire",
  "Highland",
  "Inverness-shire",
  "Isle of Anglesey",
  "Isle of Wight",
  "Kent",
  "Kincardineshire",
  "Kinross-shire",
  "Kirkcudbrightshire",
  "Lanarkshire",
  "Lancashire",
  "Lancs",
  "Leicestershire",
  "Leics",
  "Lincolnshire",
  "Lincs",
  "Merseyside",
  "Mid Glamorgan",
  "Middlesex",
  "Middx",
  "Midlothian",
  "Monmouthshire",
  "Moray",
  "Nairnshire",
  "Norfolk",
  "North Humberside",
  "North Yorkshire",
  "Northamptonshire",
  "Northants",
  "Northumberland",
  "Notts",
  "Nottinghamshire",
  "Orkney",
  "Oxon",
  "Oxfordshire",
  "Peeblesshire",
  "Pembrokeshire",
  "Perth and Kinross",
  "Perthshire",
  "Powys",
  "Renfrewshire",
  "Rhondda Cynon Taf",
  "Ross-shire",
  "Roxburghshire",
  "Rutland",
  "S Yorks",
  "Salop",
  "Selkirkshire",
  "Shetland",
  "Shropshire",
  "Somerset",
  "South Glamorgan",
  "South Humberside",
  "South Yorkshire",
  "Staffs",
  "Staffordshire",
  "Stirlingshire",
  "Suffolk",
  "Surrey",
  "Sutherland",
  "Torfaen",
  "Tyne and Wear",
  "Vale of Glamorgan",
  "W Midlands",
  "W Sussex",
  "W Yorks",
  "Warks",
  "Warwickshire",
  "West Glamorgan",
  "West Lothian",
  "West Midlands",
  "West Sussex",
  "West Yorkshire",
  "Wigtownshire",
  "Wilts",
  "Wiltshire",
  "Worcs",
  "Worcestershire",
];

export { GB_COUNTIES, GB_THOROUGHFARE_DESCRIPTORS };
