// The demo page's own words, in the two languages it speaks. A `{name}` in a line is filled in when it is shown.
// The library's own messages (a validation finding, a list of changes) are its English and are shown as they are;
// in Japanese each finding's code is explained in Japanese first.
export const WORDS = {
  en: {
    pageApi: "API reference",
    pitch:
      "Parse, validate, format and compare addresses from the US, Canada and Japan, in TypeScript. Type in any panel and the answer appears, worked out by the package itself, with the call that made it.",
    name: "Named for parse-address, which it replaces call for call, plus Canada, Japan, checking and formatting.",
    nameLink: "README",
    input: "Type",
    examples: "Try",
    options: "Option",
    json: "The whole result as JSON",
    yes: "Yes",
    no: "No",
    none: "None",
    moreTitle: "Using it",
    moreText:
      "Each panel above is the package itself. Each line below is all it takes; what follows the // is what that call returns.",
    foot: "Everything is worked out in your browser by the package's own code. No address you type leaves this page.",
    country: { US: "United States", CA: "Canada", JP: "Japan" },
    // The fields of a parsed address, by their names in ParsedAddress.
    fields: {
      place: "Place",
      number: "Number",
      fraction: "Fraction",
      prefix: "Direction before",
      street: "Street",
      type: "Street type",
      suffix: "Direction after",
      secUnitType: "Unit or box",
      secUnitNum: "Unit or box number",
      city: "City",
      state: "State or province",
      zip: "ZIP or postal code",
      plus4: "ZIP+4",
      country: "Country",
      street1: "First street",
      type1: "Its type",
      prefix1: "Direction before",
      suffix1: "Direction after",
      street2: "Second street",
      type2: "Its type",
      prefix2: "Direction before",
      suffix2: "Direction after",
      postalCode: "Postal code",
      prefecture: "Prefecture",
      prefectureCode: "Prefecture code",
      prefectureRomaji: "Prefecture in romaji",
      municipality: "Municipality",
      municipalityCode: "Municipality code",
      municipalityRomaji: "Municipality in romaji",
      town: "Town",
      chome: "Chome",
      ban: "Ban",
      go: "Go",
      block: "Block",
      building: "Building",
      floor: "Floor",
      room: "Room",
      rr: "Rural route",
      rpo: "Retail postal outlet",
      station: "Station",
      site: "Site",
      locality: "Locality",
      generalDelivery: "General delivery",
    },
    // parse
    parse_title: "Parse",
    parse_blurb:
      "Type an address from the US, Canada or Japan, written the way a person would: a street address, a PO box, the corner of two streets, French, Japanese script, romaji, full-width digits. Each part comes back in a field of its own.",
    parse_shared:
      "A Japanese address also fills the shared fields (state, city, street, number, zip) with the same values. The JSON below has them all.",
    parse_none: "Nothing here could be read as an address. Try one of the examples.",
    // validate
    validate_title: "Validate",
    validate_blurb:
      "Type an address and see whether it holds together: missing parts, a postal code in the wrong shape, or a ZIP or postal code that belongs to another state, province or prefecture. With strict postal codes on, those warnings become errors.",
    validate_strict: "Strict postal codes",
    validate_valid: "Valid",
    validate_confidence: "Confidence",
    validate_completeness: "Completeness",
    validate_country: "Country",
    validate_errors: "Errors",
    validate_warnings: "Warnings",
    validate_suggestions: "Suggestions",
    codes: {},
    // format
    format_title: "Format",
    format_blurb:
      "Type an address and it is written out the way its post office asks: USPS for the US, Canada Post for Canada, and for Japan both the Japanese order, as an envelope is addressed, and the English order. The country it was read as picks the format.",
    format_block: "Block",
    format_hyphen: "1-2-3",
    format_markers: "1丁目2番3号",
    format_usps: "USPS",
    format_canada: "Canada Post",
    format_single: "On one line",
    format_japanese: "Japanese order",
    format_english: "English order",
    format_guess: "No country was found, so it is written the USPS way.",
    format_none: "Nothing here could be read as an address, so there is nothing to format.",
    // compare
    compare_title: "Compare",
    compare_blurb:
      "Type two addresses. Both are parsed, then compared field by field, so an abbreviation and its full name, spacing and full-width digits are not differences, and a likely typo is pointed out.",
    compare_first: "First",
    compare_second: "Second",
    compare_same: "Same address",
    compare_match: "Match",
    compare_score: "Similarity",
    compare_street: "Street",
    compare_city: "City",
    compare_state: "Region",
    compare_postal: "Postal code",
    compare_differences: "Differences",
    compare_none: "One of the two could not be read as an address.",
    matches: { exact: "exact", strong: "strong", moderate: "moderate", weak: "weak", none: "none" },
    differences: { missing: "missing from one", different: "different", similar: "similar", typo: "possible typo" },
    // postal
    postal_title: "Postal code and region",
    postal_blurb:
      "Type a US ZIP code, a Canadian postal code or a Japanese postal code to find the state, province or prefecture it belongs to. Type a state, province or prefecture, by its code or its name, to list the codes it uses.",
    postal_kind: "Read as",
    postal_region: "Belongs to",
    postal_prefixes: "Codes start with",
    postal_count: "{count} prefixes",
    postal_unknown: "A postal code in the right shape, but no region uses it.",
    postal_none: "Not a postal code or a region this knows. Try 98101, M5H 2N2, 100-0005, WA, Quebec or 大阪府.",
    postal_kinds: {
      zip: "US ZIP code",
      ca: "Canadian postal code",
      jp: "Japanese postal code",
      state: "US state",
      province: "Canadian province or territory",
      prefecture: "Japanese prefecture",
    },
    // clean
    clean_title: "Clean",
    clean_blurb:
      "Paste an address typed in a hurry: stray spaces, all capitals, all lower case. It comes back tidied, with street types shortened and the case set, and a list of what was changed.",
    clean_case: "Case",
    clean_title_case: "Title Case",
    clean_upper: "CAPITALS",
    clean_asis: "As typed",
    clean_cleaned: "Cleaned",
    clean_modified: "Changed",
    clean_changes: "Changes",
    // sharing
    copy_code: "Copy code",
    copy_code_tip: "Copy the call above, ready to paste into your code",
    copy_link: "Copy link",
    copy_link_tip: "Copy a link that opens this page with this panel's address in it",
    copied_code: "The code is copied.",
    copied_link: "The link is copied.",
    copy_failed: "This browser would not copy. Select the text and copy it yourself.",
    // clean, as a chain
    clean_steps: "Step by step",
    clean_typed: "Typed",
    clean_postal: "Post office format",
    clean_postal_as: "As {format} writes it",
    clean_no_postal: "The cleaned address could not be read, so it has no post office format.",
    clean_formats: { formatUSPS: "USPS", formatCanadaPost: "Canada Post", formatJapanese: "Japan Post" },
    // japan
    japan_title: "Japan, part by part",
    japan_blurb:
      "Type a Japanese address, in Japanese script or in romaji. Each part is shown as written, beside its reading and romaji from the tables and its official code, then written out both ways and checked against the tables: the postal code's prefecture and the municipality's.",
    japan_part: "Part",
    japan_written: "Japanese",
    japan_reading: "Reading",
    japan_romaji: "Romaji",
    japan_code: "Code",
    japan_parts: {
      postalCode: "Postal code",
      prefecture: "Prefecture",
      municipality: "Municipality",
      streetDirections: "Kyoto directions",
      town: "Town",
      block: "Block",
      building: "Building",
      floor: "Floor",
      room: "Room",
    },
    japan_delivers: "Delivers to {name}",
    japan_unknown: "Not in the tables",
    japan_japanese: "Japanese order",
    japan_english: "English order",
    japan_check: "Check",
    japan_none: "Nothing here names a place in Japan. Try one of the examples.",
    // bulk
    bulk_title: "Paste a list",
    bulk_blurb:
      "Paste addresses one to a line, from the US, Canada and Japan mixed as they come. Each is parsed, checked and written the way its post office asks, in a table you can save as CSV, JSON or text.",
    bulk_list: "List",
    bulk_try: "Try",
    bulk_sample: "A mixed list",
    bulk_sample_tip:
      "Fill the box with eleven addresses: tidy and untidy, three countries, and one line that is not an address",
    bulk_clear: "Empty",
    bulk_clear_tip: "Empty the box",
    bulk_save: "Save",
    bulk_csv_tip: "Save the table as CSV, for a spreadsheet, with the Japanese fields too",
    bulk_json_tip: "Save every line's whole result, its findings and its post office format, as JSON",
    bulk_txt_tip: "Save one cleaned address per line, as plain text; a line that could not be read is kept as it was",
    bulk_table: "Results, one row per line",
    bulk_empty: "Paste addresses in the box, one to a line, or press A mixed list.",
    bulk_summary: "{read} of {total} read, {clean} with nothing to flag",
    bulk_limit: "Only the first {limit} lines are read here, to keep the page quick. The package itself has no limit.",
    bulk_unread: "Not an address",
    bulk_kinds: { US: "US", CA: "Canada", JP: "Japan", other: "No country", none: "Not read" },
    bulk_cols: {
      input: "As pasted",
      country: "Country",
      number: "Number",
      street: "Street or town",
      unit: "Unit",
      city: "City",
      region: "Region",
      postal: "Postal code",
      check: "Check",
      formatted: "Post office format",
    },
    // corpus
    corpus_title: "The test corpus, run in your browser",
    corpus_blurb:
      "Every case of the package's address corpus: USPS Publication 28, Canada Post's guidelines, libpostal, parse-address's shapes and Geolonia's Japanese test addresses. Load it and each case is parsed here, now, and held to what it expects. The few the parser still gets wrong are listed with what comes out instead.",
    corpus_load: "Load and run every case",
    corpus_loading: "Running…",
    corpus_failed: "The corpus could not be loaded.",
    corpus_headline: "{pass} of {total} pass; {wrong} known gaps",
    corpus_bar: "{pass} of {total} pass",
    corpus_country: "Country",
    corpus_all: "All",
    corpus_us: "US",
    corpus_canada: "Canada",
    corpus_japan: "Japan",
    corpus_wrong: "Only the ones still wrong",
    corpus_wrong_tip: "Show only the cases the parser does not get right yet",
    corpus_search: "Find",
    corpus_count: "Showing {shown} of {matching} matching cases",
    corpus_case_pass: "Passes",
    corpus_case_todo: "Known gap",
    corpus_case_fail: "Fails",
    corpus_expected: "Expected",
    corpus_got: "Got",
    corpus_note: "Why",
    corpus_null: "null: not an address",
    // Example chips, by panel.
    chips: {
      parse: {
        us: "Washington, DC",
        landmark: "A landmark",
        pobox: "PO box",
        corner: "Intersection",
        toronto: "Toronto",
        french: "French",
        kanji: "Japanese",
        romaji: "Romaji",
        fullwidth: "Full-width",
      },
      validate: {
        zip: "ZIP of another state",
        province: "Another province",
        prefecture: "Another prefecture",
        complete: "Complete",
        japan: "Japan, correct",
        short: "Incomplete",
      },
      format: { japan: "Japan", romaji: "Japan in romaji", us: "US with a unit", canada: "Canada", pobox: "PO box" },
      compare: {
        abbreviations: "Abbreviations",
        typo: "A typo",
        canada: "Canada",
        fullwidth: "Full-width",
        different: "Different",
      },
      clean: { capitals: "All capitals", spaces: "Stray spaces", canada: "Canada", japan: "Japan" },
      japan: {
        kyoto: "Kyoto directions",
        tokyo: "Kanji numerals",
        sapporo: "Sapporo grid",
        romaji: "Romaji",
        rural: "Rural 大字",
        sakai: "Sakai's 丁",
        merged: "A merged city",
      },
    },
  },
  ja: {
    pageApi: "API（英語）",
    pitch:
      "米国、カナダ、日本の住所を解析・検証・書式化・比較する TypeScript パッケージです。どのパネルも、入力するとすぐに結果が表示されます。結果はこのパッケージ自体が計算したもので、そのときの呼び出しも併せて示します。",
    name: "名前は parse-address にちなんでいます。parse-address の代わりに同じ呼び出し方のまま使え、さらにカナダと日本の住所、検証、書式化にも対応しています。",
    nameLink: "README（英語）",
    input: "入力",
    examples: "例",
    options: "設定",
    json: "結果全体（JSON）",
    yes: "はい",
    no: "いいえ",
    none: "なし",
    moreTitle: "使い方",
    moreText:
      "上の各パネルでは、このパッケージ自体が動いています。下のコードは、どれも1行で完結します。// の後ろは、その呼び出しの戻り値です。",
    foot: "処理はすべて、このパッケージ自体のコードがお使いのブラウザー内で行います。入力した住所がこのページの外に送信されることはありません。",
    country: { US: "米国", CA: "カナダ", JP: "日本" },
    fields: {
      place: "施設名",
      number: "番地",
      fraction: "番地の分数",
      prefix: "前に付く方角",
      street: "通り名",
      type: "通りの種類",
      suffix: "後ろに付く方角",
      secUnitType: "部屋・私書箱の種類",
      secUnitNum: "部屋・私書箱の番号",
      city: "都市",
      state: "州",
      zip: "郵便番号",
      plus4: "ZIP+4",
      country: "国",
      street1: "一つ目の通り",
      type1: "その種類",
      prefix1: "前に付く方角",
      suffix1: "後ろに付く方角",
      street2: "二つ目の通り",
      type2: "その種類",
      prefix2: "前に付く方角",
      suffix2: "後ろに付く方角",
      postalCode: "郵便番号",
      prefecture: "都道府県",
      prefectureCode: "都道府県コード",
      prefectureRomaji: "都道府県（ローマ字）",
      municipality: "市区町村",
      municipalityCode: "市区町村コード",
      municipalityRomaji: "市区町村（ローマ字）",
      town: "町域",
      chome: "丁目",
      ban: "番",
      go: "号",
      block: "丁目・番地",
      building: "建物名",
      floor: "階",
      room: "部屋番号",
      rr: "ルーラルルート",
      rpo: "郵便取扱所",
      station: "郵便局",
      site: "サイト番号",
      locality: "地区",
      generalDelivery: "局留め",
    },
    parse_title: "住所の解析",
    parse_blurb:
      "米国、カナダ、日本の住所を、ふだん書くとおりに入力します。番地のある住所、私書箱、二つの通りの交差点、フランス語、日本語の表記、ローマ字、全角数字にも対応します。住所の各部分が、それぞれの項目に分かれて返ります。",
    parse_shared:
      "日本の住所では、共通の項目（state、city、street、number、zip）にも同じ値が入ります。すべての項目は下の JSON で確認できます。",
    parse_none: "住所として読み取れませんでした。例のどれかを試してください。",
    validate_title: "住所の検証",
    validate_blurb:
      "住所を入力すると、矛盾がないかを調べます。欠けている部分、形式の正しくない郵便番号、別の州や都道府県の郵便番号などを見つけます。郵便番号の厳密な検査をオンにすると、これらの警告はエラーになります。",
    validate_strict: "郵便番号を厳密に検査",
    validate_valid: "有効",
    validate_confidence: "信頼度",
    validate_completeness: "完全度",
    validate_country: "国",
    validate_errors: "エラー",
    validate_warnings: "警告",
    validate_suggestions: "提案",
    // Each finding's code, said in Japanese; the library's English message follows it.
    codes: {
      AMBIGUOUS_MUNICIPALITY: "同じ名前の市区町村が複数の都道府県にあり、どれか特定できません。",
      INCOMPLETE_ADDRESS: "住所が不完全です。",
      INVALID_POSTAL_FORMAT: "郵便番号の形式が正しくありません。",
      INVALID_STREET_NUMBER: "番地が数字で始まっていません。",
      MISSING_CITY: "都市名がありません。",
      MISSING_LOCATION: "都市名も州もありません。",
      MISSING_POSTAL_CODE: "郵便番号がありません。",
      MISSING_STATE: "州名がありません。",
      MISSING_STREET_NAME: "通り名がありません。",
      MISSING_STREET_NUMBER: "番地がありません。",
      MISSING_STREET_TYPE: "通りの種類（St、Ave など）がありません。",
      MUNICIPALITY_PREFECTURE_MISMATCH: "市区町村が、書かれている都道府県にありません。",
      POSTAL_COUNTRY_MISMATCH: "郵便番号の形式が、住所の国と合いません。",
      POSTAL_REGION_MISMATCH: "郵便番号が、別の州や都道府県のものです。",
      QUESTIONABLE_POSTAL_FORMAT: "郵便番号の形式が正しくない可能性があります。",
      SHORT_STREET_NAME: "通り名が短すぎるようです。",
      UNPARSEABLE: "住所として読み取れませんでした。",
      UNRECOGNIZED_MUNICIPALITY: "市区町村が一覧にありません。",
      UNRECOGNIZED_POSTAL_CODE: "この上3桁で始まる郵便番号はありません。",
      UNRECOGNIZED_STATE: "州名を認識できません。",
    },
    format_title: "住所の書式化",
    format_blurb:
      "住所を入力すると、その国の郵便の決まりに沿った書き方に整えます。米国は USPS、カナダは Canada Post の書式です。日本の住所は、封筒の宛名と同じ日本式の順序と、英語式の順序の両方で出力します。どの書式を使うかは、住所から判定した国で決まります。",
    format_block: "番地の書き方",
    format_hyphen: "1-2-3",
    format_markers: "1丁目2番3号",
    format_usps: "USPS",
    format_canada: "Canada Post",
    format_single: "1行表記",
    format_japanese: "日本式の表記",
    format_english: "英語式の表記",
    format_guess: "国を判定できなかったため、USPS の書式で出力しています。",
    format_none: "住所として読み取れないため、書式化できません。",
    compare_title: "住所の比較",
    compare_blurb:
      "二つの住所を入力します。どちらも解析してから項目ごとに比べるため、略語と正式名、空白、全角数字の違いは違いとみなしません。打ち間違いらしい箇所は指摘します。",
    compare_first: "住所1",
    compare_second: "住所2",
    compare_same: "同じ住所",
    compare_match: "一致の度合い",
    compare_score: "類似度",
    compare_street: "通り",
    compare_city: "都市",
    compare_state: "州・都道府県",
    compare_postal: "郵便番号",
    compare_differences: "相違点",
    compare_none: "どちらかが住所として読み取れませんでした。",
    matches: {
      exact: "完全一致",
      strong: "ほぼ一致",
      moderate: "ある程度一致",
      weak: "わずかに一致",
      none: "不一致",
    },
    differences: { missing: "片方にない", different: "異なる", similar: "似ている", typo: "打ち間違いの可能性" },
    postal_title: "郵便番号と地域",
    postal_blurb:
      "米国の ZIP コード、カナダや日本の郵便番号を入力すると、その番号が属する州や都道府県がわかります。州や都道府県をコードか名前で入力すると、そこで使われる番号の先頭部分を一覧にします。",
    postal_kind: "種類",
    postal_region: "属する地域",
    postal_prefixes: "番号の先頭",
    postal_count: "{count}件",
    postal_unknown: "郵便番号の形式ですが、どの地域にも該当しません。",
    postal_none:
      "郵便番号としても地域としても読み取れません。98101、M5H 2N2、100-0005、WA、Quebec、大阪府 などを試してください。",
    postal_kinds: {
      zip: "米国の ZIP コード",
      ca: "カナダの郵便番号",
      jp: "日本の郵便番号",
      state: "米国の州",
      province: "カナダの州・準州",
      prefecture: "日本の都道府県",
    },
    clean_title: "表記の整理",
    clean_blurb:
      "急いで入力したような住所を貼り付けます。余分な空白や、すべて大文字・すべて小文字の住所も扱えます。通りの種類を略語にし、大文字と小文字をそろえて返します。何を変えたかも一覧にします。",
    clean_case: "大文字・小文字",
    clean_title_case: "語頭だけ大文字",
    clean_upper: "すべて大文字",
    clean_asis: "そのまま",
    clean_cleaned: "整えた住所",
    clean_modified: "変更の有無",
    clean_changes: "変更点",
    // sharing
    copy_code: "コードをコピー",
    copy_code_tip: "上の呼び出しを、そのまま貼り付けられる形でコピーします",
    copy_link: "リンクをコピー",
    copy_link_tip: "このパネルの住所を入力した状態でこのページを開くリンクをコピーします",
    copied_code: "コードをコピーしました。",
    copied_link: "リンクをコピーしました。",
    copy_failed: "このブラウザーではコピーできませんでした。テキストを選択して、手動でコピーしてください。",
    // clean, as a chain
    clean_steps: "整理の流れ",
    clean_typed: "入力",
    clean_postal: "郵便の書式",
    clean_postal_as: "書式：{format}",
    clean_no_postal: "整えた住所を読み取れなかったため、郵便の書式では表示できません。",
    clean_formats: { formatUSPS: "USPS", formatCanadaPost: "カナダ郵便", formatJapanese: "日本郵便" },
    // japan
    japan_title: "日本の住所を部分ごとに",
    japan_blurb:
      "日本の住所を、日本語またはローマ字で入力します。各部分を、書かれたとおりの形で、データにある読み・ローマ字・公式コードと並べて表示します。続けて、日本語の順と英語の順の両方で書き直し、郵便番号が示す都道府県と、市区町村が属する都道府県が合っているかをデータと照らして確認します。",
    japan_part: "部分",
    japan_written: "日本語",
    japan_reading: "読み",
    japan_romaji: "ローマ字",
    japan_code: "コード",
    japan_parts: {
      postalCode: "郵便番号",
      prefecture: "都道府県",
      municipality: "市区町村",
      streetDirections: "京都の通り名",
      town: "町域",
      block: "丁目・番地",
      building: "建物",
      floor: "階",
      room: "部屋",
    },
    japan_delivers: "配達先：{name}",
    japan_unknown: "データにありません",
    japan_japanese: "日本語の順",
    japan_english: "英語の順",
    japan_check: "確認",
    japan_none: "日本の地名が見つかりません。例のどれかを試してください。",
    // bulk
    bulk_title: "一覧を貼り付け",
    bulk_blurb:
      "住所を1行に1件ずつ貼り付けます。米国、カナダ、日本の住所が混ざっていてもかまいません。1件ずつ解析・検証し、それぞれの国の郵便の書式で書き直して表にします。表は CSV、JSON、テキストで保存できます。",
    bulk_list: "一覧",
    bulk_try: "例",
    bulk_sample: "混ざった一覧",
    bulk_sample_tip: "入力欄に11行の住所を入れます。整った住所と乱れた住所、3か国分、住所ではない行が1行含まれます",
    bulk_clear: "空にする",
    bulk_clear_tip: "入力欄を空にします",
    bulk_save: "保存",
    bulk_csv_tip: "表を表計算ソフト用の CSV で保存します。日本の住所の項目も含みます",
    bulk_json_tip: "各行の結果全体、検証結果、郵便の書式を JSON で保存します",
    bulk_txt_tip: "整えた住所を1行に1件ずつ、テキストで保存します。読み取れなかった行はそのまま残します",
    bulk_table: "結果（1行につき1件）",
    bulk_empty: "入力欄に住所を1行に1件ずつ貼り付けるか、「混ざった一覧」を押してください。",
    bulk_summary: "{total} 件中 {read} 件を読み取り、うち {clean} 件は指摘なし",
    bulk_limit:
      "ページの動作を軽く保つため、ここでは最初の {limit} 行だけを読み取ります。パッケージ自体に上限はありません。",
    bulk_unread: "住所ではありません",
    bulk_kinds: { US: "米国", CA: "カナダ", JP: "日本", other: "国不明", none: "読み取れず" },
    bulk_cols: {
      input: "貼り付けた住所",
      country: "国",
      number: "番地",
      street: "通り・町名",
      unit: "部屋など",
      city: "都市・市区町村",
      region: "州・都道府県",
      postal: "郵便番号",
      check: "検証",
      formatted: "郵便の書式",
    },
    // corpus
    corpus_title: "テスト用の住所データを、このブラウザーで実行",
    corpus_blurb:
      "このパッケージのテスト用住所データ（USPS Publication 28、カナダ郵便のガイドライン、libpostal、parse-address の住所パターン、Geolonia の日本の住所テストデータ）をすべて収録しています。読み込むと、この場ですべての例を解析し、期待される結果と照らし合わせます。まだ正しく読めない少数の例は、実際に出た結果とともに一覧にします。",
    corpus_load: "読み込んで実行",
    corpus_loading: "実行中…",
    corpus_failed: "テスト用の住所データを読み込めませんでした。",
    corpus_headline: "{total} 件中 {pass} 件が合格、既知の未対応は {wrong} 件",
    corpus_bar: "{total} 件中 {pass} 件が合格",
    corpus_country: "国",
    corpus_all: "すべて",
    corpus_us: "米国",
    corpus_canada: "カナダ",
    corpus_japan: "日本",
    corpus_wrong: "未対応の例だけ",
    corpus_wrong_tip: "まだ正しく読めない例だけを表示します",
    corpus_search: "検索",
    corpus_count: "該当する {matching} 件のうち {shown} 件を表示",
    corpus_case_pass: "合格",
    corpus_case_todo: "既知の未対応",
    corpus_case_fail: "不合格",
    corpus_expected: "期待される結果",
    corpus_got: "実際の結果",
    corpus_note: "理由",
    corpus_null: "null（住所ではない）",
    chips: {
      parse: {
        us: "ワシントンDC",
        landmark: "建物名つき",
        pobox: "私書箱",
        corner: "交差点",
        toronto: "トロント",
        french: "フランス語",
        kanji: "日本語",
        romaji: "ローマ字",
        fullwidth: "全角数字",
      },
      validate: {
        zip: "他州の ZIP",
        province: "他州の郵便番号",
        prefecture: "他県の郵便番号",
        complete: "完全な住所",
        japan: "正しい日本の住所",
        short: "不完全な住所",
      },
      format: {
        japan: "日本",
        romaji: "日本（ローマ字）",
        us: "米国（部屋番号つき）",
        canada: "カナダ",
        pobox: "私書箱",
      },
      compare: {
        abbreviations: "略語と正式名",
        typo: "打ち間違い",
        canada: "カナダ",
        fullwidth: "全角と半角",
        different: "別の住所",
      },
      clean: { capitals: "すべて大文字", spaces: "余分な空白", canada: "カナダ", japan: "日本" },
      japan: {
        kyoto: "京都の通り名",
        tokyo: "漢数字",
        sapporo: "札幌の条丁目",
        romaji: "ローマ字",
        rural: "大字の地番",
        sakai: "堺市の「丁」",
        merged: "合併した市",
      },
    },
  },
};
